variable "Sg" {}
variable "Sg_ssh" {}
variable "Ami" {}
variable "Instance" {}
variable "Subnet_id" {}
variable "Public_ip_boolean" {}
variable "Security_group" {}
variable "Tag_name" {}
variable "User_data_install_jenkins" {}
variable "Public_Key" {}